metadata:
  favicon: ''
  code: "<style>\n  .apartment nb-card {\n  \tcursor: pointer;\n  }\n  \n  .apartment nb-card:hover {\n  \tbackground-color: #E8EEFB;\n  }\n  \n  .ellipsis h1, .ellipsis p {\n    white-space: nowrap;\n    overflow: hidden;\n    text-overflow: ellipsis;\n    display: block!important;\n  }\n  \n  ub-horizontal-menu a[nbButton].active, ub-horizontal-menu a[nbButton]:hover {\n    background-color: rgb(69 112 246 / 37%)!important;\n  }\n  \n  .no-shadow button {\n    filter: none!important;\n  }\n</style>"
  title: New app
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
